query fethcPerfil($id: Int, $estado: Boolean) {
  gustos(
    order_by: { id: asc }
    where: { perfil_id: { _eq: $id }, delete_at: { _is_null: $estado } }
  ) {
    bebida
    comida
    id
    perfil_id
    perfile {
      name
      id
    }
    delete_at
  }
}
