mutation InsertPhone($objects:[person_phones_insert_input!]!) {
  __typename
insert_person_phones(objects: $objects, on_conflict: {constraint: person_phones_pkey, update_columns: id}){
    returning {
      id
      number
      person_id
      country_id
    }
    affected_rows
  }
}
