mutation MyMutation2($number: String, $country: bigint, $person_id:uuid) {
  insert_person_phones(objects: { number: $number, country_id: $country, person_id:$person_id }) {
    returning {
      number
      country_id
      id
    }
  }
}
