mutation insertPerfil(
  $bebida: String
  $comida: String
  $name: String
  $precio: money
) {
  insert_gustos(
    objects: {
      bebida: $bebida
      precio: $precio
      comida: $comida
      perfile: { data: { name: $name } }
    }
  ) {
    returning {
      perfile {
        id
        name
      }
      bebida
      comida
    }
  }
}
