mutation MyMutation(
  $person_id: uuid
  $number: String
  $country: bigint
  $id: uuid
) {
  __typename
  update_person_phones(
    _set: { number: $number, country_id: $country }
    where: { id: { _eq: $id } }
  ) {
    affected_rows
    returning {
      number
      id
      country_id
    }
  }
}
